[project]
name = "inquirer"
version = "3.4.0"
description = "Collection of common interactive command line user interfaces, based on Inquirer.js"
authors = [{name = "Miguel Ángel García", email = "miguelangel.garcia@gmail.com"}]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

dependencies = [
    "blessed>=1.19.0",
    "readchar>=4.2.0",
    "editor>=1.6.0",
]
requires-python = ">=3.10,<4.0"

[project.urls]
Homepage = "https://github.com/magmax/python-inquirer"
Repository = "https://github.com/magmax/python-inquirer"
Documentation = "https://python-inquirer.readthedocs.io"

[project.optional-dependencies]
dev = [
    "bandit>=1.7.4",
    "flake8>=6.1.0",
    "flake8-docstrings>=1.6.0",
    "Flake8-pyproject>=1.2.3",
    "furo>=2022.9.29",
    "isort>=5.10.1",
    "pexpect>=4.8.0",
    "pre-commit>=2.17.0",
    "pre-commit-hooks>=4.3.0",
    "pyupgrade>=2.31.1",
    "safety>=2.3.1",
    "sphinx>=5.3.0",
    "sphinx-autobuild>=2021.3.14"
]

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["inquirer", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 97

[tool.ruff]
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
ignore = ["E501"]

[tool.flake8]
select = ["B","B9","C","DAR","E","F","N","S","W"]
ignore = ["W503"]
max-line-length = 119
docstring-convention = "google"
